server:
  port: 8000
spring:
  application.name: prodigal-like
  mvc:
    servlet:
      path: /api
  profiles:
    active: local
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prodigal_thumb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    # Redis 配置
    redis:
      database: 0
      host: xxx
      password: xxx
      timeout: 5000
      port: 6379
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#  basic:
#    enable: true
#    username: lang
#    password: lang
  openapi:
    title: "Prodigal Like 接口文档"
    version: v1.0
    description: "Prodigal Like 接口文档"
    concat: Lang
    group:
      default:
        group-name: "local"
        api-rule: package
        api-rule-resources:
          - com.prodigal.system.controller

